runtime: nodejs18
service: default

instance_class: F2

automatic_scaling:
  min_instances: 1
  max_instances: 4
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.75

env_variables:
  NODE_ENV: production
  JWT_SECRET: 8277jwkta71
  GOOGLE_CLIENT_ID: 97213665719-l6gk58pu68jovl3pjkaji21ubi7cjqq3.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET: 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
  FIREBASE_PROJECT_ID: righ-spell
 

handlers:
  - url: /.*  
    script: auto

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 15
